import './globals.css';
import { ReactNode } from 'react';
import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter, Space_Grotesk } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '',
  description: 'Generated by create next app'
};

type Props = { children: ReactNode };

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className={clsx(inter.className, spaceGrotesk.className)}>{children}</body>
    </html>
  );
}
